Repository open-company/open-company-web, pull requests merged in 2018-10, with the labels that each got.

#649 Cancel signup by logging out the user.
  scss/partials/_onboard_wrapper.scss
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for review

#654 Mobile board dropdown arrow
  scss/partials/_dashboard_layout.scss
Labels: ready for deploy

#655 Whats new
  resources/public/img/ML/menu_whats_new.svg
  resources/public/img/ML/menu_whats_new_hover.svg
  resources/public/js/externs.js
  scss/partials/_menu.scss
  site/oc/pages.clj
  src/oc/web/components/ui/menu.cljs
Labels: ready for deploy

#656 Don't add drafts to must see data in app state.
  src/oc/web/stores/activity.cljs
Labels: ready for review

#658 Final website fixes
  resources/pages/pricing.edn
  scss/partials/_pricing.scss
  scss/public/css/app.main.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/about.cljs
  src/oc/web/components/home_page.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/slack.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/shared_misc.cljs
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/urls.cljs
Labels: reviewing

#660 Support links
  resources/public/img/ML/support.svg
  resources/public/js/externs.js
  scss/partials/_navigation_sidebar.scss
  site/oc/pages.clj
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/lib/chat.cljs
Labels: ready for deploy

#653 Agree to comment icons
  resources/public/img/ML/comment_agree_hover.svg
  resources/public/img/ML/comment_agree_off.svg
  scss/partials/_stream_comments.scss
Labels: ready for deploy

#652 Ignore changes if a video id hasn't been set yet.
  src/oc/web/actions/activity.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for review

#661 Update NUX
  resources/public/img/ML/add_post_tooltip_box.png
  resources/public/img/ML/add_post_tooltip_box@2x.png
  resources/public/img/ML/add_post_tooltip_box_second_user.png
  resources/public/img/ML/add_post_tooltip_box_second_user@2x.png
  resources/public/img/ML/dismiss_tooltip_x.svg
  resources/public/img/ML/draft_post_tooltip_box.png
  resources/public/img/ML/draft_post_tooltip_box@2x.png
  resources/public/img/ML/draft_post_tooltip_box_mobile.png
  resources/public/img/ML/draft_post_tooltip_box_mobile@2x.png
  resources/public/img/ML/post_added_tooltip_box.png
  resources/public/img/ML/post_added_tooltip_box@2x.png
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_onboard_wrapper.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/nux.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/org.cljs
Labels: reviewing

#662 Do not show covershot selection on mobile, only on desktop.
  src/oc/web/components/ui/ziggeo.cljs
Labels: reviewing

#663 Show the empty notifications message on mobile.
  scss/partials/_user_notifications.scss
Labels: reviewing

#666 Remove Must See toggle from contextual menu
  src/oc/web/components/ui/more_menu.cljs
Labels: ready for deploy

#665 Show private or public icons besides section name on mobile.
  resources/public/img/ML/board_private.svg
  resources/public/img/ML/board_public.svg
  scss/partials/_dashboard_layout.scss
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/dashboard_layout.cljs
Labels: ready for deploy

#667 Body is always deep-navy color.
  scss/partials/_stream_item.scss
Labels: ready for deploy

#668 Mobile no volume
  scss/partials/_stream_item.scss
Labels: ready for deploy

#670 Fix cmail scroll on iOS
  scss/partials/_cmail.scss
Labels: ready for deploy

#671 Add text-rendering css rule.
  scss/modules/_fonts.scss
Labels: ready for deploy

#674 Site fixes
  resources/public/img/ML/key_announcements_icon.svg
  resources/public/img/ML/stories_icon.svg
  resources/public/img/ML/strategic_plans_icon.svg
  resources/public/img/ML/team_updates_icon.svg
  scss/partials/_about.scss
  scss/partials/_home_page.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  site/oc/pages.clj
  src/oc/web/components/pricing.cljs
  src/oc/web/components/ui/shared_misc.cljs
Labels: ready for deploy

#675 Remove Blog link from the header and mobile site menu.
  scss/partials/_site_mobile_menu.scss
  site/oc/core.clj
  src/oc/web/components/ui/site_header.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
Labels: reviewing

#672 Video image instead of player to improve performance.
  resources/public/img/ML/play.svg
  resources/public/img/ML/video-spinner.gif
  scss/partials/_cmail.scss
  scss/partials/_stream_item.scss
  scss/partials/_ziggeo.scss
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/ziggeo.cljs
  src/oc/web/utils/activity.cljs
Labels: awaiting revision

#676 Fix avatar issue in user profile.
  src/oc/web/components/user_profile.cljs
Labels: ready for deploy

#677 Tweak to the last screen in NUX
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#678 Remove double border on org logo.
  scss/partials/_org_settings.scss
Labels: ready for deploy

#679 Fix infinite spinner
  src/oc/web/components/org_dashboard.cljs
Labels: ready for deploy

#680 Mobile navigation fixes.
  scss/partials/_navigation_sidebar.scss
Labels: ready for deploy

#681 Copy tweaks
  resources/public/img/ML/testimonial_1_logo.png
  resources/public/img/ML/testimonial_1_logo@2x.png
  scss/partials/_about.scss
  scss/partials/_home_page.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  scss/partials/_site_footer.scss
  scss/partials/_slack.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/home_page.cljs
  src/oc/web/components/slack.cljs
  src/oc/web/components/ui/shared_misc.cljs
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
  src/oc/web/urls.cljs
Labels: ready for deploy

#683 Press kit page.
  resources/pages/press_kig.edn
  resources/public/img/ML/press_kit_homepage.png
  resources/public/img/ML/press_kit_homepage@2x.png
  resources/public/img/ML/press_kit_play.svg
  resources/public/js/externs.js
  scss/partials/_press_kit.scss
  scss/partials/_slack_lander.scss
  scss/public/css/app.main.scss
  site/oc/core.clj
  site/oc/pages.clj
  site/oc/server.clj
  src/oc/web/components/press_kit.cljs
  src/oc/web/components/ui/shared_misc.cljs
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/core.cljs
  src/oc/web/urls.cljs
Labels: ready for deploy

#684 PH banner
  resources/public/img/ML/ph_banner_bg.png
  resources/public/img/ML/ph_banner_bg@2x.png
  resources/public/img/ML/ph_banner_cat.png
  resources/public/img/ML/ph_banner_cat@2x.png
  resources/public/img/ML/ph_banner_close.svg
  resources/public/js/static-js.js
  scss/partials/_ph_banner.scss
  scss/public/css/app.main.scss
  site/oc/core.clj
Labels: ready for deploy

#682 Fix shaky again
  scss/partials/_activity_not_found.scss
  src/oc/web/actions/org.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/activity_not_found.cljs
Labels: ready for deploy

#685 Mobile video width
  scss/partials/_stream_item.scss
Labels: ready for deploy

#687 Drift users data
  resources/public/js/externs.js
  src/oc/web/actions/user.cljs
Labels: URGENT, ready for deploy

#686 Zindex fixes
  scss/partials/_activity_move.scss
  scss/partials/_activity_share.scss
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_org_settings.scss
  scss/partials/_section_editor.scss
Labels: URGENT, ready for deploy

#690 Gather slack channel data even if you aren't an admin.
  src/oc/web/actions/team.cljs
  src/oc/web/api.cljs
Labels: reviewing

#688 Truncate org name
  src/oc/web/actions/org.cljs
Labels: ready for review

#689 Wall of difference
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/media_video_modal.cljs
  src/oc/web/lib/image_upload.cljs
  src/oc/web/mixins/activity.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#691 Org name length ui
  scss/mixins/_org.scss
  scss/partials/_menu.scss
  scss/partials/_org_settings.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/user_profile_personal_tab.cljs
  src/oc/web/utils/org.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#697 Use FullStory only on React app, not on static website
  site/oc/core.clj
Labels: ready for review

#692 Section settings button
  resources/public/img/ML/section_settings_gear.svg
  scss/partials/_dashboard_layout.scss
  scss/partials/_section_editor.scss
  src/oc/web/components/dashboard_layout.cljs
Labels: ready for deploy

#694 Drift chat fixes for dynamic pages
  src/oc/web/components/about.cljs
  src/oc/web/components/press_kit.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/site_footer.cljs
Labels: ready for deploy

#698 Fix slack orgs icon
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#699 Prod video qa
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/mixins/_activity.scss
  src/oc/web/components/stream_item.cljs
Labels: reviewing

#693 Embed loom video just like vimeo/youtube.
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/media_video_modal.cljs
Labels: reviewing

#702 New & edit parameters
  src/oc/web/actions/activity.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/ui/empty_board.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/router.cljs
Labels: ready for deploy

#703 Ziggeo time of 5 minutes
  README.md
  resources/public/lib/ziggeo/playerjs-adapter.js
  resources/public/lib/ziggeo/ziggeo.css
  resources/public/lib/ziggeo/ziggeo.js
  script/local_ziggeo_dev.sh
  src/oc/web/components/ui/ziggeo.cljs
Labels: reviewing

#704 Authenticate to notification service.
  src/oc/web/lib/ws_notify_client.cljs
Labels: reviewing

#706 Mention with only email
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/CustomizedTagComponent.js
  scss/partials/_oc_mentions.scss
  src/oc/web/mixins/mention.cljs
Labels: ready for deploy

#707 Update the regular expression to check the email domain.
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#708 Show section editor on FullStory
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#709 Don't restart NUX on email verification
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#710 Wrt improvements
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/components/all_posts.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/ziggeo.cljs
  src/oc/web/events/expand_event.cljs
  src/oc/web/mixins/ui.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#712 Dismiss add Slack bot tooltip when user clicks CTA button
  src/oc/web/components/dashboard_layout.cljs
Labels: ready for deploy

#713 WURFL not available
  src/oc/web/lib/responsive.cljs
Labels: ready for deploy

#711 Share rage click
  scss/partials/_activity_share.scss
  src/oc/web/components/ui/activity_share.cljs
Labels: reviewing
