Repository open-company/open-company-web, pull requests merged in 2018-08, with the labels that each got.

#590 Fix onboard overlay
  src/oc/web/actions/nux.cljs
Labels: ready for deploy

#586 Google sso
  resources/public/img/ML/google_signin.svg
  scss/partials/_login_overlay.scss
  scss/partials/_onboard_wrapper.scss
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/urls.cljs
Labels: awaiting revision

#591 Email domain nux
  resources/public/img/ML/slack_normal.svg
  scss/partials/_login_overlay.scss
  scss/partials/_onboard_wrapper.scss
  src/oc/web/actions/org.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: awaiting revision

#593 Contributor invite
  src/oc/web/api.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for review

#594 Bugfix: Slack team info lost
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#597 Sort boards in alpha order when listing for move an activity.
  src/oc/web/components/ui/activity_move.cljs
Labels: ready for deploy

#598 Fix last used section
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#599 Fix arrow position for search box.
  scss/partials/_search.scss
Labels: ready for deploy

#600 Truncate long section names
  scss/partials/_activity_card.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_section_editor.scss
Labels: ready for deploy

#601 Preload some images.
  scss/partials/_dashboard_layout.scss
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_stream_comments.scss
Labels: ready for deploy
