Repository open-company/open-company-web, pull requests merged in 2018-09, with the labels that each got.

#602 Fix user avatars
  scss/mixins/_reusable.scss
  scss/partials/_comments_summary.scss
Labels: ready for deploy

#606 Update empty states.
  resources/public/img/ML/empty_state_ap_section.svg
  resources/public/img/ML/empty_state_background.svg
  resources/public/img/ML/empty_state_drafts.svg
  resources/public/img/ML/empty_state_ms.svg
  scss/partials/_empty_board.scss
  scss/partials/_navigation_sidebar.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/ui/empty_board.cljs
Labels: ready for deploy

#607 Marketing site refresh
  resources/public/img/ML/homepage_screenshots_update_team.png
  resources/public/img/ML/homepage_screenshots_update_team@2x.png
  resources/public/img/ML/homepage_screenshots_update_team_mobile.png
  resources/public/img/ML/homepage_screenshots_update_team_mobile@2x.png
  resources/public/img/ML/testimonial_1_image.jpg
  resources/public/img/ML/testimonial_1_image.png
  resources/public/img/ML/testimonial_1_image@2x.png
  resources/public/img/ML/testimonial_1_logo.png
  resources/public/img/ML/testimonial_1_logo@2x.png
  resources/public/img/ML/testimonial_2_image.png
  resources/public/img/ML/testimonial_2_image@2x.png
  resources/public/img/ML/testimonial_2_logo.png
  resources/public/img/ML/testimonial_2_logo@2x.png
  resources/public/img/ML/testimonial_3_image.png
  resources/public/img/ML/testimonial_3_image@2x.png
  resources/public/img/ML/testimonial_3_logo.png
  resources/public/img/ML/testimonial_3_logo@2x.png
  scss/partials/_home_page.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  scss/partials/_slack.scss
  site/oc/pages.clj
  src/oc/web/components/home_page.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/slack.cljs
  src/oc/web/components/ui/shared_misc.cljs
Labels: ready for deploy

#609 Small tweaks
  resources/public/img/ML/horizontal_ellipsis.svg
  resources/public/img/ML/stream_tile_share.svg
  scss/partials/_more_menu.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_stream_comments.scss
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/stream_item.cljs
Labels: ready for deploy

#608 Last section standing
  scss/partials/_section_editor.scss
  src/oc/web/actions/section.cljs
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#610 Fix empty board create button
  scss/partials/_empty_board.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/ui/empty_board.cljs
Labels: ready for deploy

#605 Nux 2.0
  resources/public/img/ML/add_post_tooltip_box.png
  resources/public/img/ML/add_post_tooltip_box@2x.png
  resources/public/img/ML/company_avatar_green_plus.svg
  resources/public/img/ML/dismiss_tooltip_x.svg
  resources/public/img/ML/post_added_tooltip_box.png
  resources/public/img/ML/post_added_tooltip_box@2x.png
  scss/mixins/_org.scss
  scss/partials/_activity_attachments.scss
  scss/partials/_alert_modal.scss
  scss/partials/_all_caught_up.scss
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_entry_edit.scss
  scss/partials/_list_boards.scss
  scss/partials/_login_overlay.scss
  scss/partials/_media_chart_modal.scss
  scss/partials/_menu.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_onboard_overlay.scss
  scss/partials/_onboard_wrapper.scss
  scss/partials/_org_settings.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_placeholder.scss
  scss/partials/_select2.scss
  scss/partials/_slack_bot_modal.scss
  scss/partials/_stream_item.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nux.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/activity_attachments.cljs
  src/oc/web/components/ui/alert_modal.cljs
  src/oc/web/components/ui/media_chart_modal.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/onboard_overlay.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_avatar.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/components/ui/slack_bot_modal.cljs
  src/oc/web/components/user_profile_notifications_tab.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/router.cljs
  src/oc/web/stores/org.cljs
  src/oc/web/urls.cljs
  src/oc/web/utils/activity.cljs
  src/oc/web/utils/draft.cljs
Labels: ready for deploy

#612 Fast UI tweaks from the Paper doc.
  resources/public/img/ML/invite_people.svg
  scss/mixins/_activity.scss
  scss/partials/_add_comment.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_emoji_picker.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_stream_item.scss
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/add_comment.cljs
Labels: ready for deploy

#614 Restyle ME context menu.
  resources/public/img/ML/context_menu_anchor.svg
  resources/public/img/ML/context_menu_bold.svg
  resources/public/img/ML/context_menu_h2.svg
  resources/public/img/ML/context_menu_italic.svg
  resources/public/img/ML/context_menu_list.svg
  scss/partials/_medium_editor.scss
  scss/public/css/app.main.scss
  src/oc/web/components/rich_body_editor.cljs
Labels: ready for deploy

#615 Goodbye black bands
  scss/partials/_stream_item.scss
  scss/partials/_ziggeo.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/ziggeo.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#617 Fix post added tooltip layout and copy.
  resources/public/img/ML/post_added_tooltip_box.png
  resources/public/img/ML/post_added_tooltip_box@2x.png
  scss/partials/_dashboard_layout.scss
  src/oc/web/components/dashboard_layout.cljs
Labels: ready for deploy

#618 Fix mobile font size.
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_stream_item.scss
Labels: ready for deploy

#623 Fix cmail tooltips
  src/oc/web/components/cmail.cljs
Labels: ready for deploy

#621 Inline comment agree
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
Labels: ready for deploy

#622 Fix single emoji comment
  scss/partials/_add_comment.scss
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/emoji_picker.cljs
Labels: ready for deploy

#624 Turn off Slack mirror when selecting private section
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#625 Use tooltips when Slack is disabled in invite panel.
  scss/partials/_org_settings_invite_panel.scss
  src/oc/web/components/ui/org_settings_invite_panel.cljs
Labels: ready for deploy

#626 Fullscreen cleanup
  scss/partials/_alert_modal.scss
  scss/partials/_cmail.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/activity.cljs
Labels: reviewing

#627 Change top and bottom margin of all nux tooltips from 32 to 8 pixels.
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_stream_item.scss
Labels: ready for deploy

#629 Must see new post
  src/oc/web/actions/activity.cljs
Labels: ready for deploy

#631 Mobile density improvements
  scss/partials/_stream_item.scss
Labels: reviewing

#633 Refresh draft count (org data) when receiving a draft section change
  src/oc/web/actions/section.cljs
  src/oc/web/components/navigation_sidebar.cljs
Labels: awaiting revision

#616 Close cmail when the activity being edited is deleted
  src/oc/web/components/cmail.cljs
  src/oc/web/stores/activity.cljs
Labels: reviewing

#632 Pre flight 2
  src/oc/web/actions/section.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#634 Auto save avatars
  scss/mixins/_org.scss
  scss/partials/_org_settings.scss
  src/oc/web/actions/org.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/ui/org_avatar.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/org.cljs
  src/oc/web/stores/user.cljs
Labels: ready for deploy

#637 New section cmail
  src/oc/web/actions/activity.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/stores/activity.cljs
Labels: ready for deploy

#636 Centre search bar
  resources/public/img/ML/spyglass.svg
  resources/public/img/ML/spyglass_active.svg
  scss/mixins/_org.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_menu.scss
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_org_settings.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_search.scss
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
  src/oc/web/stores/search.cljs
Labels: reviewing

#641 Fix multiple drafts while autosaving.
  src/oc/web/stores/activity.cljs
Labels: URGENT, reviewing

#639 Use fullscreen edit for published post
  src/oc/web/actions/activity.cljs
Labels: ready for deploy

#640 Fullscreen post restyle
  scss/partials/_fullscreen_post.scss
  scss/partials/_login_button.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_section_stream.scss
  scss/partials/_stream_item.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/section.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/login_button.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/section.cljs
Labels: ready for deploy

#635 Save when closing and auto save after adding an attachment.
  src/oc/web/actions/activity.cljs
  src/oc/web/components/cmail.cljs
Labels: ready for review

#643 Mobile edit restyle
  resources/public/img/ML/cmail_capture_video_icon.svg
  resources/public/img/ML/cmail_footer_must_see_icon.svg
  resources/public/img/ML/cmail_footer_must_see_icon_on.svg
  resources/public/img/ML/edit_pencil_icon_white.svg
  resources/public/img/ML/mobile_capture_video_icon.svg
  resources/public/img/ML/remove_video_icon.svg
  scss/partials/_cmail.scss
  scss/partials/_entry_edit.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#644 Add an argument to the redirect url to indicate a slack team is being added.
  src/oc/web/actions/team.cljs
Labels: ready for deploy

#645 Sections picker restyle
  resources/public/img/ML/section_add_mobile_close.svg
  resources/public/img/ML/section_preflight_checkmark.svg
  resources/public/img/ML/sections_picker_add_section.svg
  scss/partials/_alert_modal.scss
  scss/partials/_carrot_checkbox.scss
  scss/partials/_cmail.scss
  scss/partials/_section_editor.scss
  scss/partials/_sections_picker.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/carrot_checkbox.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/sections_picker.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#588 Mentions
  README.md
  resources/public/img/ML/back_green_arrow.svg
  resources/public/img/ML/notification_bell.svg
  resources/public/img/ML/notification_bell_active.svg
  resources/public/img/ML/notification_green_dot.svg
  resources/public/img/ML/notification_read_bt.svg
  resources/public/img/ML/slack_mention_icon.svg
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/CustomizedTagComponent.js
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/LICENSE
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/index.js
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/index.min.js
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/index.min.js.map
  resources/public/lib/MediumEditorExtensions/MediumEditorTCMention/mention-panel.min.css
  script/compile_assets.sh
  script/minimize-css.sh
  scss/partials/_menu.scss
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_notifications.scss
  scss/partials/_oc_mentions.scss
  scss/partials/_user_notifications.scss
  scss/partials/_user_profile.scss
  scss/public/css/app.main.scss
  site/oc/pages.clj
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/user_avatar.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/lib/ws_notify_client.cljs
  src/oc/web/mixins/mention.cljs
  src/oc/web/stores/user.cljs
  src/oc/web/utils/comment.cljs
  src/oc/web/utils/mention.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#646 Use search result limit since we don't have paging
  src/oc/web/components/search.cljs
  src/oc/web/stores/search.cljs
Labels: ready for review
