Repository open-company/open-company-web, pull requests merged in 2018-04, with the labels that each got.

#453 Settings refresh data
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/org_settings.cljs
Labels: ready for deploy

#446 Fix comments in public sections
  src/oc/web/components/stream_view_item.cljs
Labels: reviewing

#448 Fix user email update
  src/oc/web/actions/user.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/stores/user.cljs
Labels: ready for deploy

#435 REFACTOR: Move all section related code to action creators and store.
  src/oc/web/actions.cljs
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/api.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/entries_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/sections_picker.cljs
  src/oc/web/core.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/section.cljs
Labels: reviewing

#447 Emoji comments
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/utils/comment.cljs
Labels: ready for deploy

#460 Fixes the issue of the Save button being stuck as 'Saving....'
  src/oc/web/actions/org.cljs
  src/oc/web/stores/org.cljs
Labels: reviewing

#461 Your digest
  resources/public/js/static-js.js
  scss/partials/_home_page.scss
  scss/partials/_site_header.scss
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/components/ui/site_header.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
  src/oc/web/lib/utils.cljs
Labels: reviewing

#464 BUG: Token refresh
  src/oc/web/api.cljs
Labels: reviewing

#468 Preload sections on AP
  src/oc/web/actions/org.cljs
Labels: URGENT, ready for deploy

#442 Fix delete section
  src/oc/web/actions.cljs
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/ui/empty_org.cljs
  src/oc/web/stores/section.cljs
Labels: ready for deploy

#462 Change Post to... with Sections.
  src/oc/web/components/ui/sections_picker.cljs
Labels: reviewing

#463 Mobile navigation
  scss/partials/_navigation_sidebar.scss
Labels: ready for deploy

#466 Mobile navigation header
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  src/oc/web/actions/search.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
  src/oc/web/stores/search.cljs
Labels: ready for deploy

#465 Drift
  resources/pages/pricing.edn
  resources/public/js/drift.js
  site/oc/core.clj
Labels: ready for deploy

#469 Sentry OC-BETA-WEB-4R
  src/oc/web/components/secure_activity.cljs
Labels: ready for deploy

#470 Paste long html
  src/oc/web/components/rich_body_editor.cljs
Labels: ready for deploy

#471 Private section no users
  scss/partials/_section_editor.scss
  src/oc/web/actions/team.cljs
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#455 Remove unused keys from dispatcher data.
  src/oc/web/dispatcher.cljs
Labels: ready for deploy

#458 BUG: MediumEditor and Firefox
  scss/partials/_entry_edit.scss
  src/oc/web/components/entry_edit.cljs
  src/oc/web/lib/utils.cljs
Labels: reviewing

#456 If at least one of the teams has Slack enabled let the user select it.
  src/oc/web/components/user_profile.cljs
Labels: reviewing

#467 Homepage redirect
  resources/public/js/static-js.js
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/urls.cljs
Labels: ready for deploy

#472 Update page title
  site/oc/core.clj
  site/oc/pages.clj
Labels: reviewing

#457 Fix duplicate tooltips
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/drafts_layout.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/stream_view_item.cljs
Labels: reviewing

#476 Add comments on public section
  scss/partials/_fullscreen_post.scss
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#473 Improve render-on-resize mixin
  src/oc/web/mixins/ui.cljs
Labels: ready for deploy

#477 Update page title
  site/oc/core.clj
  site/oc/pages.clj
Labels: ready for deploy

#475 Section label
  scss/partials/_activity_card.scss
  src/oc/web/components/activity_card.cljs
Labels: reviewing

#454 REFACTOR: Change service messages refactor.
  src/oc/web/actions.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/entries_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/stores/org.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/section.cljs
Labels: reviewing

#481 Replace org placeholder avatar in onboard screen.
  resources/public/img/ML/onboard_plus_icon.png
  resources/public/img/ML/onboard_plus_icon.svg
  resources/public/img/ML/onboard_plus_icon@2x.png
  scss/partials/_onboard_wrapper.scss
Labels: ready for deploy

#482 BUG: grid more menu is hidden
  scss/partials/_activity_card.scss
Labels: ready for deploy

#483 Sort sections by name in the section picker.
  src/oc/web/components/ui/sections_picker.cljs
Labels: ready for deploy

#484 Fix drafts layout and truncation.
  scss/partials/_drafts_layout.scss
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#485 Fix activity url
  src/oc/web/actions/org.cljs
  src/oc/web/actions/section.cljs
Labels: ready for deploy

#486 Email wall restyle
  resources/public/img/ML/email_wall.svg
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#489 Fix home page jump for logged in users.
  resources/public/js/static-js.js
  resources/public/lib/jwt_decode/jwt-decode.js
  resources/public/lib/jwt_decode/jwt-decode.min.js
  script/compile_assets.sh
  site/oc/core.clj
  site/oc/pages.clj
Labels: ready for deploy

#479 REFACTOR: Cleanup stores that have oc.web.router dependencies.
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/section.cljs
Labels: reviewing

#488 Invite logo
  src/oc/web/api.cljs
Labels: ready for deploy

#490 Fix invite people tooltip appear
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/navigation_sidebar.cljs
Labels: ready for deploy

#493 Stream section tag
  scss/mixins/_activity.scss
  scss/partials/_activity_card.scss
  scss/partials/_stream_view_item.scss
  src/oc/web/components/stream_view_item.cljs
Labels: ready for deploy

#492 Clean underline text on body paste
  src/oc/web/components/rich_body_editor.cljs
Labels: ready for deploy

#494 Fix filestack sources
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/utils/org.cljs
  src/oc/web/utils/user.cljs
Labels: reviewing

#495 Fix CDN urls
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#496 Fix user avatar default.
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#498 Fix create section
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#497 Fix compose button
  scss/partials/_dashboard_layout.scss
  src/oc/web/components/dashboard_layout.cljs
Labels: ready for deploy

#499 Fullstory
  README.md
  resources/public/js/externs.js
  resources/public/lib/autotrack/google-analytics.js
  resources/public/lib/fullstory.js
  script/compile_assets.sh
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/drafts_layout.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/ui/org_settings_team_panel.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/user_avatar.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/lib/raven.cljs
Labels: reviewing
