Repository open-company/open-company-web, pull requests merged in 2018-03, with the labels that each got.

#391 Copy copy changes
  scss/partials/_shared_misc.scss
  site/oc/pages.clj
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/ui/shared_misc.cljs
Labels: ready for deploy

#392 Fix all posts placement in the app shell container.
  scss/partials/_all_posts.scss
  scss/partials/_dashboard_layout.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/lib/responsive.cljs
Labels: ready for review

#393 Change boards with your digest and sections.
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/navigation_sidebar.cljs
Labels: ready for review

#388 comment delete fix
  src/oc/web/components/comments.cljs
Labels: ready for deploy

#373 Needed to support private board notifications.
  src/oc/web/actions.cljs
  src/oc/web/api.cljs
Labels: reviewing

#387 Fullscreen post
  resources/public/img/ML/editing_pen.png
  resources/public/img/ML/editing_pen@2x.png
  resources/public/img/ML/fullscreen_back_arrow.png
  resources/public/img/ML/fullscreen_back_arrow@2x.png
  resources/public/img/ML/fullscreen_closing_x.png
  resources/public/img/ML/fullscreen_closing_x@2x.png
  resources/public/img/ML/post_publish.png
  resources/public/img/ML/post_publish@2x.png
  resources/public/img/ML/vertical_ellipsis.svg
  scss/mixins/_activity.scss
  scss/mixins/_base.scss
  scss/partials/_activity_card.scss
  scss/partials/_activity_modal.scss
  scss/partials/_add_comment.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_view_item.scss
  scss/public/css/app.main.scss
  src/oc/web/actions.cljs
  src/oc/web/actions/activity.cljs
  src/oc/web/components/activity_modal.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/responsive.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/utils/comment.cljs
Labels: URGENT, reviewing

#394 Mobile AP fixes
  resources/public/img/ML/all_posts_icon.png
  resources/public/img/ML/all_posts_icon@2x.png
  scss/partials/_all_posts.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_navbar.scss
  scss/partials/_stream_view_item.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#398 Fix continue reading
  scss/partials/_stream_view_item.scss
  src/oc/web/components/stream_view_item.cljs
Labels: ready for deploy

#401 Fix go to digest button
  resources/public/img/ML/digest_white.svg
  resources/public/js/static-js.js
  scss/partials/_site_header.scss
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/ui/site_header.cljs
Labels: ready for deploy

#404 Remove Share your thoughts from FoC.
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/entries_layout.cljs
Labels: reviewing

#396 Attachments
  resources/public/img/ML/clear_attachments_x.svg
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_stream_view_attachments.scss
  scss/partials/_stream_view_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/activity_attachments.cljs
  src/oc/web/components/ui/stream_view_attachments.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#403 Navigation menu style
  resources/public/img/ML/digest_icon_green.svg
  resources/public/img/ML/digest_icon_grey.svg
  resources/public/img/ML/drafts_icon_green.svg
  resources/public/img/ML/drafts_icon_grey.svg
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/navigation_sidebar.cljs
Labels: reviewing

#397 Sections stream
  resources/public/img/ML/attachments_file_download.svg
  resources/public/img/ML/attachments_file_download_green.svg
  resources/public/img/ML/attachments_file_icon.svg
  resources/public/img/ML/attachments_icon.svg
  resources/public/img/ML/grid_view_button.svg
  resources/public/img/ML/more_menu_delete.svg
  resources/public/img/ML/more_menu_edit.svg
  resources/public/img/ML/more_menu_share.svg
  resources/public/img/ML/posted_in_icon.svg
  resources/public/img/ML/stream_view_button.svg
  resources/public/img/ML/vertical_ellipsis_deep_navy.svg
  resources/public/img/ML/vertical_ellipsis_ui_grey.svg
  scss/partials/_activity_attachments.scss
  scss/partials/_activity_card.scss
  scss/partials/_add_comment.scss
  scss/partials/_all_posts.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_drafts_layout.scss
  scss/partials/_emoji_picker.scss
  scss/partials/_entries_layout.scss
  scss/partials/_entry_edit.scss
  scss/partials/_fullscreen_post.scss
  scss/partials/_interactions_summary.scss
  scss/partials/_more_menu.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_section_stream.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_view_attachments.scss
  scss/partials/_stream_view_item.scss
  scss/public/css/app.main.scss
  scss/vars/main.scss
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/all_posts.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/drafts_layout.cljs
  src/oc/web/components/entries_layout.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/activity_attachments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/interactions_summary.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/stream_view_attachments.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/responsive.cljs
  src/oc/web/mixins/ui.cljs
  src/oc/web/router.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#407 Mobile NUX fix
  resources/public/img/ML/mobile_onboard_overlay.png
  resources/public/img/ML/mobile_onboard_overlay@2x.png
  scss/partials/_onboard_overlay.scss
Labels: ready for review

#408 Remove section icon in grid view
  resources/public/img/ML/posted_in_icon.svg
  scss/partials/_activity_card.scss
Labels: ready for deploy

#405 Navbar alignment
  scss/mixins/_org.scss
  scss/partials/_base.scss
  scss/partials/_list_boards.scss
  scss/partials/_menu.scss
  scss/partials/_mobile_boards_list.scss
  scss/partials/_navbar.scss
  scss/partials/_org_avatar.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_search.scss
  scss/partials/_trend_bar.scss
  scss/public/css/app.main.scss
  scss/vars/main.scss
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/trend_bar.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/org_avatar.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
Labels: ready for deploy

#389 Don't ignore the same user's comment updates.
  src/oc/web/actions.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/lib/ws_interaction_client.cljs
  src/oc/web/stores/comment.cljs
Labels: reviewing

#409 Mobile navigation
  resources/public/img/ML/board_public.svg
  resources/public/img/ML/board_public_green.svg
  scss/partials/_navigation_sidebar.scss
  scss/partials/_onboard_overlay.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/onboard_overlay.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/mixins/ui.cljs
Labels: ready for deploy

#411 Mobile section button
  scss/partials/_entry_edit.scss
Labels: ready for review

#412 Mobile dismiss section
  scss/partials/_entry_edit.scss
  scss/partials/_section_editor.scss
  src/oc/web/components/ui/section_editor.cljs
Labels: reviewing

#413 Attachments refinements
  scss/partials/_activity_attachments.scss
  scss/partials/_activity_card.scss
  scss/partials/_stream_view_attachments.scss
  src/oc/web/components/activity_card.cljs
Labels: reviewing

#414 Comments summary fix
  resources/public/img/ML/mobile_comments_chevron.svg
  scss/partials/_stream_view_item.scss
Labels: ready for deploy

#415 Fix edit view title.
  scss/partials/_entry_edit.scss
  src/oc/web/components/entry_edit.cljs
Labels: ready for deploy

#416 Mobile add section tooltip.
  scss/partials/_sections_picker.scss
  src/oc/web/components/ui/sections_picker.cljs
Labels: ready for deploy

#417 Redirects on post creation
  src/oc/web/actions.cljs
  src/oc/web/components/entry_edit.cljs
Labels: reviewing

#418 Increase the delete draft target
  scss/partials/_drafts_layout.scss
Labels: ready for deploy

#419 Emoji picker position
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
Labels: ready for deploy

#420 Fix grid/stream view on mobile
  src/oc/web/components/dashboard_layout.cljs
Labels: reviewing

#423 Fix strip empty tags function
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#422 Do not focus headline if already focused
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
Labels: ready for deploy

#421 Mobile continue reading
  src/oc/web/components/stream_view_item.cljs
Labels: reviewing

#406 Changes to the technical documentation.
  LICENSE
  README.md
  docs/GOOGLE_ANALYTICS.md
  docs/TECHNICAL_DESIGN.md
  docs/flux-diagram-white-background.png
  docs/flux-simple-f8-diagram-with-client-action-1300w.png
  src/oc/web/actions.cljs
Labels: ready for deploy

#424 Pricing
  resources/public/img/ML/pricing_balloon_big_purple.png
  resources/public/img/ML/pricing_balloon_big_purple@2x.png
  resources/public/img/ML/pricing_balloon_big_red.png
  resources/public/img/ML/pricing_balloon_big_red@2x.png
  resources/public/img/ML/pricing_balloon_small_blue.png
  resources/public/img/ML/pricing_balloon_small_blue@2x.png
  resources/public/img/ML/pricing_more_info.svg
  resources/public/img/ML/pricing_table_check.svg
  resources/public/js/externs.js
  resources/public/js/static-js.js
  resources/public/lib/autotrack/google-analytics.js
  scss/partials/_home_page.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  scss/partials/_slack.scss
  site/oc/core.clj
  site/oc/pages.clj
  site/oc/server.clj
  src/oc/web/components/home_page.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/slack.cljs
  src/oc/web/components/ui/shared_misc.cljs
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
Labels: reviewing

#395 Watch boards that are in all posts.
  src/oc/web/actions.cljs
  src/oc/web/lib/ws_interaction_client.cljs
  src/oc/web/stores/reaction.cljs
Labels: ready for deploy

#410 Post move
  scss/partials/_fullscreen_post.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/api.cljs
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/ui/slack_channels_dropdown.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/activity.cljs
Labels: ready for deploy

#427 REFACTOR: Move the comment actions to the correct namespace
  src/oc/web/actions.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/ws_interaction_client.cljs
  src/oc/web/stores/comment.cljs
Labels: reviewing

#428 Fix post indexing for reaction store
  src/oc/web/stores/reaction.cljs
Labels: reviewing

#430 REFACTOR: Move team related actions
  src/oc/web/actions.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/ui/org_settings_team_panel.cljs
  src/oc/web/components/ui/slack_users_dropdown.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/team.cljs
  src/oc/web/stores/user.cljs
Labels: ready for deploy

#433 Fix auth-settings key
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/stores/user.cljs
Labels: reviewing

#432 REFACTOR: Subscription refactor
  src/oc/web/actions.cljs
  src/oc/web/actions/subscription.cljs
  src/oc/web/api.cljs
  src/oc/web/core.cljs
  src/oc/web/stores/subscription.cljs
Labels: ready for deploy

#434 REFACTOR: Use core.async pub/sub for the websocket clients.
  src/oc/web/actions.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/lib/ws_change_client.cljs
  src/oc/web/lib/ws_interaction_client.cljs
Labels: ready for deploy

#429 REFACTOR: Move UI related actions
  src/oc/web/actions.cljs
  src/oc/web/actions/error_banner.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/components/drafts_layout.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/error_banner.cljs
  src/oc/web/components/fullscreen_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_editor.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/alert_modal.cljs
  src/oc/web/components/ui/made_with_carrot_modal.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/ui/org_settings_team_panel.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/site_header.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
  src/oc/web/components/ui/whats_new_modal.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/error_banner.cljs
  src/oc/web/stores/user.cljs
Labels: reviewing

#439 BUG: can't create post with new section
  src/oc/web/actions/activity.cljs
  src/oc/web/components/entry_edit.cljs
Labels: ready for deploy

#431 REFACTOR: Org refactor
  src/oc/web/actions.cljs
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/core.cljs
  src/oc/web/stores/org.cljs
Labels: reviewing

#441 More cleanup
  scss/partials/_carrot_tip.scss
  scss/public/css/app.main.scss
  site/oc/pages.clj
  src/oc/web/actions/comment.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/carrot_tip.cljs
  src/oc/web/stores/comment.cljs
Labels: reviewing

#440 Fix nux comment
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/stream_view_item.cljs
Labels: ready for deploy

#445 Bug fix for watching org changes from change service.
  src/oc/web/actions/org.cljs
  src/oc/web/lib/ws_change_client.cljs
Labels: reviewing

#450 Fix user roles chevron click
  scss/partials/_user_type_dropdown.scss
Labels: ready for deploy

#451 Fix empty invite row
  src/oc/web/actions/team.cljs
Labels: ready for deploy
