Repository open-company/open-company-web, pull requests merged in 2018-02, with the labels that each got.

#369 Google analytics javascript
  docs/GOOGLE_ANALYTICS.md
  resources/public/js/externs.js
  resources/public/lib/autotrack/autotrack.js
  resources/public/lib/autotrack/google-analytics.js
  script/compile_assets.sh
  site/oc/core.clj
  site/oc/pages.clj
Labels: reviewing

#364 New NUX
  resources/public/img/ML/black_back_arrow.svg
  resources/public/img/ML/blue_back_arrow.svg
  resources/public/img/ML/empty_board.svg
  resources/public/img/ML/gray_back_x.svg
  resources/public/img/ML/mobile_empty_board.png
  resources/public/img/ML/mobile_empty_board@2x.png
  resources/public/img/ML/mobile_nux_il_1.png
  resources/public/img/ML/mobile_nux_il_1@2x.png
  resources/public/img/ML/mobile_nux_il_2.png
  resources/public/img/ML/mobile_nux_il_2@2x.png
  resources/public/img/ML/mobile_nux_il_3.png
  resources/public/img/ML/mobile_nux_il_3@2x.png
  resources/public/img/ML/onboard_mobile_green_balloon.png
  resources/public/img/ML/onboard_mobile_green_balloon@2x.png
  resources/public/img/ML/onboard_mobile_green_balloon_1.png
  resources/public/img/ML/onboard_mobile_green_balloon_1@2x.png
  resources/public/img/ML/onboard_mobile_purple_balloon.png
  resources/public/img/ML/onboard_mobile_purple_balloon@2x.png
  resources/public/img/ML/onboard_mobile_red_balloon.png
  resources/public/img/ML/onboard_mobile_red_balloon@2x.png
  resources/public/img/ML/onboard_mobile_yellow_balloon.png
  resources/public/img/ML/onboard_mobile_yellow_balloon@2x.png
  resources/public/img/ML/onboard_overlay_il_1.png
  resources/public/img/ML/onboard_overlay_il_1@2x.png
  resources/public/img/ML/onboard_overlay_il_last.png
  resources/public/img/ML/onboard_overlay_il_last@2x.png
  resources/public/img/ML/white_continue_arrow.svg
  scss/partials/_carrot_tip.scss
  scss/partials/_empty_board.scss
  scss/partials/_entry_edit.scss
  scss/partials/_loading.scss
  scss/partials/_login_overlay.scss
  scss/partials/_onboard_overlay.scss
  scss/partials/_onboard_wrapper.scss
  scss/partials/_site_mobile_menu.scss
  scss/vendor/_filestack.scss
  site/oc/pages.clj
  src/oc/web/actions.cljs
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/carrot_tip.cljs
  src/oc/web/components/ui/empty_board.cljs
  src/oc/web/components/ui/loading.cljs
  src/oc/web/components/ui/login_button.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/onboard_overlay.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/site_mobile_menu.cljs
  src/oc/web/core.cljs
Labels: ready for deploy

#372 Search components optimizations
  src/oc/web/components/search.cljs
Labels: ready for deploy

#370 Stream view
  resources/public/img/ML/comment_reaction_green.svg
  resources/public/img/ML/comment_reaction_grey.svg
  resources/public/img/ML/no_comments_sleep.png
  resources/public/img/ML/no_comments_sleep@2x.png
  resources/public/img/ML/reply_comment_shape.svg
  scss/partials/_add_comment.scss
  scss/partials/_comments.scss
  scss/partials/_emoji_picker.scss
  scss/partials/_reactions.scss
  scss/partials/_shared_misc.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_view_attachments.scss
  scss/partials/_stream_view_item.scss
  scss/public/css/app.main.scss
  src/oc/web/actions.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/api.cljs
  src/oc/web/components/activity_card.cljs
  src/oc/web/components/all_posts.cljs
  src/oc/web/components/comment_reactions.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/drafts_layout.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/activity_attachments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/interactions_summary.cljs
  src/oc/web/components/ui/media_attachments.cljs
  src/oc/web/components/ui/stream_view_attachments.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/mixins/activity.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/utils/activity.cljs
  src/oc/web/utils/comment.cljs
Labels: reviewing

#371 New post view
  resources/public/img/ML/new_post_emoji_button.png
  resources/public/img/ML/new_post_emoji_button@2x.png
  resources/public/img/ML/new_post_legend.png
  resources/public/img/ML/new_post_legend@2x.png
  resources/public/img/ML/new_post_legend_button.png
  resources/public/img/ML/new_post_legend_button@2x.png
  scss/partials/_emoji_picker.scss
  scss/partials/_entry_edit.scss
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/ui/emoji_picker.cljs
Labels: ready for deploy

#376 Fix login
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/login_overlay.cljs
Labels: URGENT, reviewing

#381 Viewer and Contributors NUX issues
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/onboard_overlay.cljs
Labels: reviewing

#379 Always show All Posts
  src/oc/web/components/navigation_sidebar.cljs
Labels: reviewing

#380 Always open All Posts
  resources/public/js/static-js.js
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#375 Copy changes
  resources/public/img/ML/about_balloon_big_purple.png
  resources/public/img/ML/about_balloon_big_purple@2x.png
  resources/public/img/ML/about_balloon_small_yellow.png
  resources/public/img/ML/about_balloon_small_yellow@2x.png
  resources/public/js/static-js.js
  scss/partials/_about.scss
  scss/partials/_home_page.scss
  scss/partials/_shared_misc.scss
  site/oc/pages.clj
  src/oc/web/components/about.cljs
  src/oc/web/components/home_page.cljs
  src/oc/web/components/ui/site_header.cljs
Labels: reviewing

#377 Stream view fixes
  resources/public/img/ML/comment_agree_off.svg
  resources/public/img/ML/comment_agree_off_hover.svg
  resources/public/img/ML/comment_agree_on.svg
  resources/public/img/ML/comment_agree_on_hover.svg
  resources/public/img/ML/comment_reaction_green.svg
  resources/public/img/ML/comment_reaction_grey.svg
  scss/mixins/_activity.scss
  scss/partials/_add_comment.scss
  scss/partials/_all_posts.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_view_attachments.scss
  scss/partials/_stream_view_item.scss
  src/oc/web/actions/comment.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_view_item.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/interactions_summary.cljs
  src/oc/web/components/ui/stream_view_attachments.cljs
Labels: reviewing

#382 Back to AP
  src/oc/web/components/entry_edit.cljs
Labels: reviewing

#374 Rum/React upgrade
  .travis.yml
  build.boot
  src/oc/web/components/search.cljs
  src/oc/web/stores/search.cljs
Labels: reviewing

#378 New post multi picker
  resources/public/img/ML/multi_picker_attachment_icon.png
  resources/public/img/ML/multi_picker_attachment_icon@2x.png
  resources/public/img/ML/multi_picker_image_icon.png
  resources/public/img/ML/multi_picker_image_icon@2x.png
  resources/public/img/ML/multi_picker_video_icon.png
  resources/public/img/ML/multi_picker_video_icon@2x.png
  resources/public/img/ML/new_post_picker_button.png
  resources/public/img/ML/new_post_picker_button@2x.png
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/partials/_entry_edit.scss
  scss/partials/_multi_picker.scss
  scss/public/css/app.main.scss
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/emoji_picker.cljs
  src/oc/web/components/ui/multi_picker.cljs
Labels: reviewing

#386 Mobile regressions
  scss/partials/_dashboard_layout.scss
  src/oc/web/components/ui/interactions_summary.cljs
  src/oc/web/components/ui/user_avatar.cljs
Labels: ready for deploy

#383 New reactions
  resources/public/img/ML/reaction_picker_icon.svg
  resources/public/img/ML/reaction_picker_icon_hover.svg
  scss/partials/_reactions.scss
  scss/partials/_stream_view_item.scss
  src/oc/web/actions.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/actions/search.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/comment_reactions.cljs
  src/oc/web/components/comments.cljs
  src/oc/web/components/entry_edit.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/lib/ws_interaction_client.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/user.cljs
Labels: ready for deploy

#384 Only render emoji-picker on click
  scss/partials/_emoji_picker.scss
  scss/partials/_reactions.scss
  src/oc/web/components/reactions.cljs
  src/oc/web/components/ui/emoji_picker.cljs
Labels: reviewing
