Repository open-company/open-company-web, pull requests merged in 2019-06, with the labels that each got.

#906 New interstitial view
  resources/public/img/ML/interstitial.svg
  resources/public/img/ML/interstitial_mobile.svg
  scss/partials/_all_posts.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_expanded_post.scss
  scss/partials/_lazy_stream.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_section_stream.scss
  scss/public/css/app.main.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/ui/lazy_stream.cljs
Labels: ready for deploy

#901 Org name max length
  .travis.yml
  README.md
  boot.properties
  build.boot
  scss/partials/_onboard_wrapper.scss
  scss/partials/_org_settings_modal.scss
  src/oc/web/actions/org.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/json.cljs
  src/oc/web/lib/prevent_route_dispatch.cljs
  src/oc/web/router.cljs
  src/oc/web/utils/activity.cljs
  src/oc/web/utils/comment.cljs
  src/oc/web/utils/org.cljs
Labels: reviewing

#912 Fix login redirect
  src/oc/web/api.cljs
  src/oc/web/components/ui/activity_not_found.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/dispatcher.cljs
Labels: URGENT, reviewing

#900 Redirect to stream view on publish
  src/oc/web/components/cmail.cljs
Labels: ready for deploy

#902 Section settings lose changes
  src/oc/web/actions/section.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/stores/section.cljs
Labels: ready for deploy

#908 Preload interstitial images
  scss/partials/_cmail.scss
  scss/partials/_lazy_stream.scss
  scss/partials/_navbar.scss
  scss/partials/_shared_misc.scss
  site/oc/pages.clj
Labels: reviewing

#913 Fullstory fixes
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/stream_attachments.cljs
Labels: ready for deploy

#905 Fix FoC timestamp tooltip
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#917 Mobile sections list dismiss
  scss/partials/_navbar.scss
  src/oc/web/components/ui/navbar.cljs
Labels: awaiting revision

#898 Fast copy changes
  scss/partials/_cmail.scss
  scss/partials/_empty_board.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_oc_mentions.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_recurring_updates_modal.scss
  scss/partials/_section_editor.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/recurring_updates_modal.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/lazy_stream.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/user_notifications_modal.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/utils/activity.cljs
Labels: reviewing

#919 Fix viewer contributor access
  src/oc/web/components/ui/empty_board.cljs
Labels: reviewing

#914 Comment reaction authors
  src/oc/web/actions/reaction.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/stores/reaction.cljs
Labels: reviewing

#911 Post sorting
  scss/mixins/_activity.scss
  scss/partials/_comments_summary.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_paginated_stream.scss
  scss/partials/_section_stream.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/cookies.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/router.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/stores/org.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/stores/section.cljs
  src/oc/web/utils/activity.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#923 Fix drafts label
  src/oc/web/utils/activity.cljs
Labels: ready for deploy

#920 Fix body truncation
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
  src/oc/web/mixins/activity.cljs
Labels: ready for deploy

#926 Fix body placeholder
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#903 List users roster
  scss/partials/_team_management_modal.scss
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/integrations_settings_modal.cljs
  src/oc/web/components/invite_settings_modal.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/ui/menu.cljs
Labels: ready for deploy

#915 Fast copy changes 2
  scss/mixins/_activity.scss
  scss/partials/_cmail.scss
  scss/partials/_edit_recurring_update_modal.scss
  scss/partials/_expanded_post.scss
  scss/partials/_section_editor.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_item.scss
  scss/partials/_wrt.scss
  src/oc/web/actions/reminder.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/stores/reminder.cljs
  src/oc/web/utils/comment.cljs
Labels: ready for deploy

#921 Mobile Cmail attachments
  scss/partials/_cmail.scss
  scss/partials/_stream_attachments.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/stream_attachments.cljs
Labels: ready for deploy

#925 Drift → Intercom
  resources/public/js/drift.js
  resources/public/js/externs.js
  resources/public/js/intercom.js
  site/oc/core.clj
  site/oc/pages.clj
  site/oc/privacy.clj
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/components/about.cljs
  src/oc/web/components/press_kit.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/site_footer.cljs
  src/oc/web/lib/chat.cljs
  src/oc/web/local_settings.cljs
Labels: reviewing

#931 Truncate notifications
  scss/partials/_user_notifications.scss
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/mixins/activity.cljs
Labels: ready for deploy

#930 Update page title
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/actions/org.cljs
Labels: ready for deploy

#928 Show comments timestamps
  scss/partials/_stream_comments.scss
Labels: ready for deploy

#927 Refresh read data
  src/oc/web/components/ui/wrt.cljs
Labels: ready for deploy

#922 Web client cleanup
  scss/partials/_carrot_box_thanks.scss
  scss/partials/_carrot_close_bt.scss
  scss/partials/_made_with_carrot_modal.scss
  scss/partials/_multi_picker.scss
  scss/partials/_org_settings.scss
  scss/partials/_org_settings_invite_panel.scss
  scss/partials/_org_settings_main_panel.scss
  scss/partials/_org_settings_team_panel.scss
  scss/partials/_reminders.scss
  scss/partials/_tile_menu.scss
  scss/partials/_user_profile.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/user.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/reminders.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/carrot_box_thanks.cljs
  src/oc/web/components/ui/carrot_close_bt.cljs
  src/oc/web/components/ui/item_input.cljs
  src/oc/web/components/ui/made_with_carrot_modal.cljs
  src/oc/web/components/ui/multi_picker.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/ui/org_settings_team_panel.cljs
  src/oc/web/components/ui/tile_menu.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/components/user_profile_modal.cljs
  src/oc/web/components/user_profile_notifications_tab.cljs
  src/oc/web/components/user_profile_personal_tab.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/ziggeo.cljs
  src/oc/web/utils/activity.cljs
Labels: ready for review

#918 Mobile FoC fixes
  resources/public/img/ML/mobile_attachment_icon.svg
  resources/public/img/ML/reaction_picker_icon_hover.svg
  scss/partials/_cmail.scss
  scss/partials/_comments_summary.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_expanded_post.scss
  scss/partials/_navbar.scss
  scss/partials/_reactions.scss
  scss/partials/_stream_attachments.scss
  scss/partials/_stream_item.scss
  scss/partials/_wrt.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/stream_attachments.cljs
Labels: ready for review
