Repository open-company/open-company-web, pull requests merged in 2019-01, with the labels that each got.

#763 Fix possible race-condition on add comment box
  src/oc/web/components/ui/add_comment.cljs
Labels: reviewing

#766 Validate that the id token has the requested secure uuid.
  src/oc/web/actions/activity.cljs
Labels: reviewing

#768 Extra settings
  scss/partials/_user_profile.scss
  src/oc/web/api.cljs
  src/oc/web/components/user_profile_notifications_tab.cljs
  src/oc/web/lib/jwt.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#771 Test for current activity id to allow share urls to work.
  src/oc/web/actions/activity.cljs
Labels: reviewing

#772 Queue websocket messages when connection is down.
  src/oc/web/ws/change_client.cljs
  src/oc/web/ws/interaction_client.cljs
  src/oc/web/ws/notify_client.cljs
  src/oc/web/ws/utils.cljs
Labels: ready for deploy

#770 Reminders
  resources/public/img/ML/reminders_logo_dark.svg
  resources/public/img/ML/reminders_logo_white.svg
  resources/public/img/ML/small_dismiss_tooltip.svg
  resources/public/js/externs.js
  scss/mixins/_reusable.scss
  scss/modules/_colors.scss
  scss/partials/_activity_not_found.scss
  scss/partials/_add_comment.scss
  scss/partials/_dropdown_list.scss
  scss/partials/_login_overlay.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_onboard_wrapper.scss
  scss/partials/_reminders.scss
  scss/partials/_user_notifications.scss
  scss/partials/_user_profile.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/nux.cljs
  src/oc/web/actions/reminder.cljs
  src/oc/web/api.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/reminders.cljs
  src/oc/web/components/ui/dropdown_list.cljs
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/local_settings.cljs
  src/oc/web/stores/reminder.cljs
  src/oc/web/utils/activity.cljs
  src/oc/web/utils/reminder.cljs
  src/oc/web/utils/user.cljs
  src/oc/web/ws/interaction_client.cljs
Labels: ready for deploy

#776 NUX tweaks
  resources/public/img/ML/add_a_slack_team_bt.png
  resources/public/img/ML/add_a_slack_team_bt@2x.png
  resources/public/img/ML/add_post_tooltip_pen.svg
  resources/public/img/ML/google_signin.svg
  resources/public/img/ML/slack_normal.svg
  resources/public/img/ML/slack_white_icon.svg
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_login_overlay.scss
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#777 Sentry NullPointer exception
  src/oc/web/components/ui/notifications.cljs
Labels: reviewing

#778 Sentry on get-reminders
  src/oc/web/actions/reminder.cljs
Labels: ready for deploy

#779 Sentry empty team name
  scss/partials/_org_settings.scss
  scss/partials/_org_settings_main_panel.scss
  src/oc/web/actions/org.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
Labels: ready for deploy

#780 More website
  resources/public/js/static-js.js
  scss/modules/_colors.scss
  scss/partials/_about.scss
  scss/partials/_home_page.scss
  scss/partials/_press_kit.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  scss/partials/_site_footer.scss
  scss/partials/_site_header.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/about.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/ui/shared_misc.cljs
Labels: ready for deploy

#781 Can add reminder
  scss/partials/_reminders.scss
  src/oc/web/components/reminders.cljs
  src/oc/web/components/ui/dropdown_list.cljs
Labels: ready for deploy

#782 Show first and last name on the same line.
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#783 Draft navigation bug
  src/oc/web/actions/activity.cljs
Labels: URGENT, ready for deploy

#790 Remove more rich content on copy paste
  src/oc/web/components/rich_body_editor.cljs
Labels: URGENT, ready for deploy

#786 Fix WS queue
  src/oc/web/ws/utils.cljs
Labels: URGENT, reviewing

#784 NUX email domain
  scss/partials/_onboard_wrapper.scss
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#785 Remove NUX invite step
  scss/partials/_onboard_wrapper.scss
  src/oc/web/actions/org.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: reviewing

#787 User timezone
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
Labels: reviewing

#788 Fix mobile login dialog
  scss/partials/_base.scss
  scss/partials/_login_overlay.scss
Labels: ready for deploy

#789 Nux tooltips tweaks
  resources/public/img/ML/dismiss_tooltip_x_small.svg
  resources/public/img/ML/floating_tooltip_top_arrow.svg
  scss/partials/_dashboard_layout.scss
  scss/partials/_reminders.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nux.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/reminders.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/dispatcher.cljs
Labels: ready for deploy

#791 Better error reporting for WS send failure
  src/oc/web/ws/utils.cljs
Labels: reviewing
