Repository open-company/open-company-web, pull requests merged in 2019-07, with the labels that each got.

#935 Comment buttons tooltips
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/dropdown_list.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/user_avatar.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/components/user_notifications_modal.cljs
  src/oc/web/components/user_profile_modal.cljs
  src/oc/web/mixins/ui.cljs
Labels: ready for deploy

#942 Remove profile url
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/urls.cljs
Labels: ready for deploy

#940 Copy share URL notification
  src/oc/web/components/ui/activity_share.cljs
Labels: ready for deploy

#939 Email domain settings
  scss/partials/_org_settings_modal.scss
  src/oc/web/components/org_settings_modal.cljs
Labels: reviewing

#937 Fix editor empty tags
  scss/mixins/_activity.scss
Labels: ready for deploy

#933 Improve initial load
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/stores/activity.cljs
Labels: ready for deploy

#943 Ms edge fixes 2
  resources/public/js/externs.js
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/core.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#936 Carrot electron desktop application
  .gitignore
  README.md
  build.boot
  resources/carrot.iconset/icon.icns
  resources/carrot.iconset/icon.ico
  resources/carrot.iconset/icon_128x128.png
  resources/carrot.iconset/icon_128x128@2x.png
  resources/carrot.iconset/icon_16x16.png
  resources/carrot.iconset/icon_16x16@2x.png
  resources/carrot.iconset/icon_256x256.png
  resources/carrot.iconset/icon_256x256@2x.png
  resources/carrot.iconset/icon_32x32.png
  resources/carrot.iconset/icon_32x32@2x.png
  resources/carrot.iconset/icon_512x512.png
  resources/carrot.iconset/icon_512x512@2x.png
  resources/electron-builder.example.env
  resources/electron/entitlements.mac.plist
  resources/electron/main.cljs.edn
  resources/electron/notarize.js
  resources/electron/renderer.js
  resources/package.json
  resources/public/js/externs.js
  resources/yarn.lock
  scss/partials/_login_wall.scss
  scss/partials/_org_dashboard.scss
  scss/public/css/app.main.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/electron/main.cljs
  src/oc/web/actions/jwt.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/login_wall.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/urls.cljs
Labels: ready for deploy

#944 Fix login redirect
  src/oc/web/actions/user.cljs
Labels: URGENT, ready for deploy

#945 Edge: avoid dotdotdot truncation
  scss/partials/_stream_item.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/stream_item.cljs
Labels: ready for deploy

#949 Frameless Mac desktop client + improved desktop tray icon
  README.md
  build.boot
  resources/carrot.iconset/icon.icns
  resources/carrot.iconset/icon.ico
  resources/carrot.iconset/icon_128x128.png
  resources/carrot.iconset/icon_128x128@2x.png
  resources/carrot.iconset/icon_16x16.png
  resources/carrot.iconset/icon_16x16@2x.png
  resources/carrot.iconset/icon_256x256.png
  resources/carrot.iconset/icon_256x256@2x.png
  resources/carrot.iconset/icon_32x32.png
  resources/carrot.iconset/icon_32x32@2x.png
  resources/carrot.iconset/icon_512x512.png
  resources/carrot.iconset/icon_512x512@2x.png
  resources/electron-builder.example.env
  resources/electron/notarize.js
  resources/electron/renderer.js
  resources/package.json
  resources/public/js/externs.js
  scss/partials/_electron.scss
  scss/partials/_login_wall.scss
  scss/partials/_navbar.scss
  scss/public/css/app.main.scss
  src/oc/electron/main.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/core.cljs
Labels: ready for review

#947 Fix sentry OC-BETA-WEB-D2
  src/oc/web/actions/activity.cljs
Labels: URGENT, ready for deploy

#948 Fix search results load
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/search.cljs
  src/oc/web/components/search.cljs
Labels: ready for deploy

#950 Force trasparent background color for links in the body.
  scss/mixins/_activity.scss
Labels: ready for deploy

#954 Desktop push notifications
  resources/electron/renderer.js
  resources/package.json
  resources/public/js/externs.js
  src/oc/electron/main.cljs
  src/oc/web/actions/notifications.cljs
Labels: ready for deploy

#958 Fix section name trimming
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#952 Quick post
  resources/public/img/ML/cmail_fullscreen_expand_black.svg
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_giphy_picker.scss
  scss/partials/_stream_attachments.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/cmail.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/actions/search.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/giphy_picker.cljs
  src/oc/web/components/ui/media_video_modal.cljs
  src/oc/web/components/ui/sections_picker.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/mixins/ui.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#961 Fix drafts count
  src/oc/web/dispatcher.cljs
Labels: URGENT, ready for deploy

#951 Fix section reads count
  src/oc/web/actions/section.cljs
Labels: ready for deploy, reviewing

#953 Fix Firefox scroll
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/activity.cljs
Labels: ready for deploy

#962 Fix quick post NUX
  scss/partials/_expanded_post.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/utils/draft.cljs
Labels: URGENT, ready for deploy

#934 Remove unused email waitlist stuff
  resources/public/js/externs.js
  resources/public/js/static-js.js
  src/oc/web/components/home_page.cljs
  src/oc/web/components/press_kit.cljs
  src/oc/web/components/pricing.cljs
  src/oc/web/components/slack_lander.cljs
  src/oc/web/components/ui/site_header.cljs
  src/oc/web/components/ui/try_it_form.cljs
  src/oc/web/local_settings.cljs
Labels: ready for review

#959 Mac traffic light styling fix + improved auto-update logic
  resources/carrot.iconset/icon.icns
  resources/carrot.iconset/icon.ico
  resources/carrot.iconset/icon_128x128.png
  resources/carrot.iconset/icon_128x128@2x.png
  resources/carrot.iconset/icon_16x16.png
  resources/carrot.iconset/icon_16x16@2x.png
  resources/carrot.iconset/icon_256x256.png
  resources/carrot.iconset/icon_256x256@2x.png
  resources/carrot.iconset/icon_32x32.png
  resources/carrot.iconset/icon_32x32@2x.png
  resources/carrot.iconset/icon_512x512.png
  resources/carrot.iconset/icon_512x512@2x.png
  resources/package.json
  scss/partials/_electron.scss
  src/oc/electron/auto_update.cljs
  src/oc/electron/main.cljs
Labels: ready for deploy

#960 Integrate Sentry with desktop app
  build.boot
  resources/package.json
  resources/yarn.lock
  src/oc/electron/main.cljs
Labels: ready for review

#970 Fix WST section manage button
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/section.cljs
Labels: URGENT, reviewing

#969 Fix private WST
  src/oc/web/stores/activity.cljs
Labels: URGENT, ready for deploy

#964 Default to current section
  src/oc/web/actions/activity.cljs
Labels: reviewing

#965 Fix board watch
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/stream_item.cljs
Labels: URGENT, ready for deploy

#967 All top right green buttons in modals should have 4 pixels radius.
  scss/partials/_edit_recurring_update_modal.scss
  scss/partials/_integrations_settings_modal.scss
  scss/partials/_invite_settings_modal.scss
  scss/partials/_org_settings_modal.scss
  scss/partials/_recurring_updates_modal.scss
  scss/partials/_section_editor.scss
  scss/partials/_team_management_modal.scss
  scss/partials/_user_notifications_modal.scss
  scss/partials/_user_profile_modal.scss
Labels: reviewing

#957 Digest links fixes
  scss/partials/_secure_activity.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/core.cljs
  src/oc/web/utils/comment.cljs
Labels: ready for deploy

#973 Fix private section creation for contributor
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/stores/section.cljs
Labels: URGENT, ready for deploy
