Repository open-company/open-company-web, pull requests merged in 2019-09, with the labels that each got.

#924 Refactor auth-link state strings to be Base64 encoded EDN maps
  build.boot
  src/oc/web/actions/org.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/stores/user.cljs
  src/oc/web/utils/user.cljs
Labels: reviewing

#1008 DnD spinner and upload percentage
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorFileDragging/filedragging.js
  scss/partials/_add_comment.scss
  scss/partials/_cmail.scss
  scss/partials/_stream_attachments.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/stream_attachments.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/image_upload.cljs
  src/oc/web/utils/medium_editor_media.cljs
Labels: URGENT, ready for deploy

#993 Mobile google signin
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/login_wall.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/expo.cljs
Labels: reviewing

#990 Desktop tweaks
  resources/carrot.iconset/icon.icns
  resources/carrot.iconset/icon.ico
  resources/carrot.iconset/icon_128x128.png
  resources/carrot.iconset/icon_128x128@2x.png
  resources/carrot.iconset/icon_16x16.png
  resources/carrot.iconset/icon_16x16@2x.png
  resources/carrot.iconset/icon_256x256.png
  resources/carrot.iconset/icon_256x256@2x.png
  resources/carrot.iconset/icon_32x32.png
  resources/carrot.iconset/icon_32x32@2x.png
  resources/carrot.iconset/icon_512x512.png
  resources/carrot.iconset/icon_512x512@2x.png
  resources/electron/renderer.js
  resources/package.json
  resources/public/js/externs.js
  src/oc/electron/main.cljs
  src/oc/web/actions/notifications.cljs
Labels: reviewing

#992 Fix notifications expiration time
  src/oc/web/actions/org.cljs
  src/oc/web/actions/reminder.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/invite_settings_modal.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/ui/ziggeo.cljs
  src/oc/web/core.cljs
Labels: ready for deploy

#995 Update native login view
  scss/partials/_login_wall.scss
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/login_wall.cljs
  src/oc/web/components/ui/section_editor.cljs
Labels: reviewing

#994 Follow-up improvements
  scss/partials/_cmail.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/follow_ups_picker.cljs
Labels: reviewing

#996 Update sections picker style
  resources/public/img/ML/board_private_green.svg
  scss/partials/_cmail.scss
  scss/partials/_sections_picker.scss
  src/oc/web/components/ui/sections_picker.cljs
Labels: reviewing

#997 FoC icons
  scss/partials/_stream_item.scss
  scss/partials/_wrt.scss
Labels: ready for deploy

#998 Expanded post date and time
  src/oc/web/components/expanded_post.cljs
Labels: reviewing

#999 Fix fullstory sessionURL
  src/oc/web/api.cljs
  src/oc/web/ws/utils.cljs
Labels: ready for deploy

#1003 Focus on body field
  src/oc/web/components/cmail.cljs
Labels: ready for deploy

#1004 Always go back to AP
  src/oc/web/actions/routing.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#1005 WST viewed opacity
  src/oc/web/components/ui/wrt.cljs
Labels: ready for deploy

#1006 Update comment buttons
  resources/public/img/ML/comment_react_emoji.svg
  resources/public/img/ML/comment_reply.svg
  resources/public/img/ML/comment_share.svg
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
Labels: ready for deploy

#1007 EmojiMart auto focus search field
  src/oc/web/components/reactions.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/emoji_picker.cljs
Labels: ready for deploy

#1014 Fix site footer background color.
  scss/partials/_site_footer.scss
Labels: ready for deploy

#1015 Fix stream items background color
  scss/partials/_dashboard_layout.scss
  scss/partials/_expanded_post.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_paginated_stream.scss
  scss/partials/_stream_item.scss
Labels: ready for deploy

#1018 Empty states tweaks
  scss/partials/_empty_board.scss
  src/oc/web/components/ui/empty_board.cljs
Labels: ready for deploy

#1019 Push notification wall tweaks
  scss/partials/_push_notifications_permission_modal.scss
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/push_notifications_permission_modal.cljs
Labels: ready for deploy

#1020 Fix comment share copy
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/more_menu.cljs
Labels: ready for deploy

#1011 File upload size
  resources/public/lib/MediumEditorExtensions/MediumEditorFileDragging/filedragging.js
  src/oc/web/lib/image_upload.cljs
  src/oc/web/local_settings.cljs
  src/oc/web/utils/medium_editor_media.cljs
Labels: ready for deploy

#1002 Performance improvement
  src/oc/web/actions/cmail.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/actions/web_app_update.cljs
  src/oc/web/api.cljs
  src/oc/web/components/carrot_abstract.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/lazy_stream.cljs
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/chat.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/utils/comment.cljs
  src/oc/web/utils/ws_client_ids.cljs
  src/oc/web/ws/change_client.cljs
  src/oc/web/ws/interaction_client.cljs
  src/oc/web/ws/notify_client.cljs
Labels: ready for deploy

#1012 Performance improvement: round 2
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/lazy_stream.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/mixins/activity.cljs
Labels: ready for deploy

#1013 Experimental section switch
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
Labels: URGENT, ready for deploy

#1025 Section switch: posts reload
  src/oc/web/actions/nav_sidebar.cljs
Labels: ready for deploy

#1001 Add comment highlight also in the secure post view.
  scss/partials/_add_comment.scss
  scss/partials/_expanded_post.scss
  scss/partials/_secure_activity.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/jwt.cljs
  src/oc/web/stores/comment.cljs
Labels: ready for deploy

#1022 Add app version in menu
  resources/electron/renderer.js
  resources/public/js/externs.js
  scss/partials/_menu.scss
  src/oc/web/components/ui/menu.cljs
  src/oc/web/core.cljs
  src/oc/web/expo.cljs
Labels: ready for deploy

#1023 Fix follow-up copy.
  scss/partials/_follow_ups_picker.scss
  scss/partials/_more_menu.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/follow_ups_picker.cljs
  src/oc/web/components/ui/more_menu.cljs
Labels: ready for deploy

#1024 Fix bold sections
  src/oc/web/stores/section.cljs
Labels: URGENT, ready for deploy

#1017 Fix fullstory session urls.
  src/oc/web/api.cljs
  src/oc/web/ws/utils.cljs
Labels: reviewing

#1028 Remove comments pre-load
  src/oc/web/components/stream_item.cljs
Labels: ready for deploy

#1032 Fix oauth state decode
  build.boot
Labels: URGENT, ready for deploy

#1026 Allow use of org and board UUIDs in URL path, which redirect to their respective slugs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/expo.cljs
  src/oc/web/router.cljs
Labels: ready for deploy

#1036 Fix activity 404
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/utils/user.cljs
Labels: URGENT, ready for deploy
