Repository open-company/open-company-web, pull requests merged in 2019-11, with the labels that each got.

#1061 Homepage copy tweaks
  resources/public/js/static-js.js
  scss/partials/_site_header.scss
  site/oc/core.clj
  site/oc/pages/index.clj
  site/oc/pages/pricing.clj
Labels: low-hanging fruit, ready for deploy

#1054 Subscription billing
  resources/public/img/ML/menu_billing.svg
  resources/public/img/ML/menu_billing_hover.svg
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  resources/public/lib/print_ascii.js
  scss/modules/_colors.scss
  scss/partials/_alert_modal.scss
  scss/partials/_cmail.scss
  scss/partials/_expanded_post.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_payments_settings_modal.scss
  scss/partials/_trial_expired_banner.scss
  scss/public/css/app.main.scss
  scss/vars/main.scss
  site/oc/pages.clj
  site/oc/pages/shared.clj
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/payments.cljs
  src/oc/web/actions/subscription.cljs
  src/oc/web/api.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/payments_settings_modal.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/login_wall.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/trial_expired_banner.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/expo.cljs
  src/oc/web/local_settings.cljs
  src/oc/web/stores/payments.cljs
  src/oc/web/stores/subscription.cljs
  src/oc/web/urls.cljs
  src/oc/web/utils/medium_editor_media.cljs
  src/oc/web/utils/stripe.cljs
Labels: ready for deploy

#1060 Working prototype of stream refresh on window focus
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/mixins/section.cljs
Labels: ready for deploy

#1055 Reverse root comments
  scss/partials/_expanded_post.scss
  scss/partials/_stream_comments.scss
  src/oc/web/components/expanded_post.cljs
  src/oc/web/utils/comment.cljs
Labels: ready for deploy

#1068 Cancel subscription
  scss/partials/_payments_settings_modal.scss
  src/oc/web/actions/payments.cljs
  src/oc/web/components/payments_settings_modal.cljs
Labels: ready for deploy

#1062 Secure activity footer tweaks
  scss/partials/_secure_activity.scss
  src/oc/web/components/secure_activity.cljs
Labels: No code-review, ready for deploy

#1063 Hide thumbnails from mobile FoC
  scss/partials/_stream_item.scss
Labels: No code-review, ready for deploy

#1064 Fix invite rows
  src/oc/web/components/invite_settings_modal.cljs
Labels: No code-review, ready for deploy

#1065 Fix time format
  src/oc/web/lib/utils.cljs
Labels: No code-review, ready for deploy

#1066 Fix mobile scrolls
  src/oc/web/mixins/ui.cljs
  src/oc/web/utils/dom.cljs
Labels: No code-review, ready for deploy

#1058 Better bot removal
  src/oc/web/actions/user.cljs
  src/oc/web/components/user_notifications_modal.cljs
Labels: low-hanging fruit, ready for deploy

#1067 Compose tweaks
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/partials/_carrot_abstract.scss
  scss/partials/_cmail.scss
  scss/partials/_post_to_button.scss
  src/oc/web/components/carrot_abstract.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/post_to_button.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#1056 Unbold sections test
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/navigation_sidebar.cljs
Labels: ready for deploy

#1070 Minor design vga
  scss/partials/_dashboard_layout.scss
  scss/partials/_navbar.scss
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
Labels: No code-review, ready for review

#1042 Remove sections preload
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/comment.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/activity_removed.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/lazy_stream.cljs
Labels: ready for deploy

#1071 ClojureScript upgrade
  boot.properties
  build.boot
Labels: ready for deploy
