Repository open-company/open-company-web, pull requests merged in 2019-08, with the labels that each got.

#975 Fix abstract autoresize field
  src/oc/web/components/cmail.cljs
Labels: URGENT, ready for deploy

#956 App update banner refresh
  scss/partials/_notifications.scss
  src/oc/electron/auto_update.cljs
  src/oc/shared/interval.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/actions/web_app_update.cljs
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/core.cljs
  src/oc/web/lib/utils.cljs
Labels: reviewing

#976 Fix NEW comments badge
  src/oc/web/stores/activity.cljs
Labels: URGENT, ready for deploy

#966 Expand images from post body
  scss/partials/_expanded_post.scss
  scss/partials/_image_modal.scss
  scss/public/css/app.main.scss
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/ui/image_modal.cljs
Labels: reviewing

#980 Fix Follow-ups pagination
  src/oc/web/components/paginated_stream.cljs
Labels: URGENT, ready for deploy

#981 Fix reads count when loading more items on AP and FU
  src/oc/web/actions/activity.cljs
Labels: URGENT, ready for deploy

#968 Rich abstract
  script/compile_assets.sh
  scss/mixins/_activity.scss
  scss/partials/_carrot_abstract.scss
  scss/partials/_cmail.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/org.cljs
  src/oc/web/components/carrot_abstract.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/mixins/ui.cljs
Labels: reviewing

#978 Headline font update
  scss/modules/_fonts.scss
Labels: reviewing

#955 Fix cut mentions
  scss/partials/_cmail.scss
Labels: reviewing

#972 Add desktop app (beta) links to the sidebar menu
  resources/electron/renderer.js
  resources/package.json
  resources/public/js/externs.js
  resources/public/js/static-js.js
  scss/partials/_menu.scss
  src/oc/web/actions/jwt.cljs
  src/oc/web/actions/notifications.cljs
  src/oc/web/actions/web_app_update.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
Labels: reviewing

#982 Desktop hotfixes
  resources/public/js/externs.js
  src/oc/electron/auto_update.cljs
Labels: URGENT

#985 Remove section picker from NUX
  scss/partials/_onboard_wrapper.scss
  scss/partials/_slack_users_dropdown.scss
  src/oc/web/actions/org.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/org.cljs
  src/oc/web/urls.cljs
Labels: URGENT, reviewing

#983 Replace static-js useragent detection with GCL implementation
  resources/public/js/externs.js
  resources/public/js/static-js.js
  src/oc/shared/useragent.cljs
  src/oc/web/actions/jwt.cljs
  src/oc/web/actions/notifications.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/actions/web_app_update.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/emoji_picker.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/urls.cljs
Labels: ready for review

#979 Mobile push notifications
  resources/public/js/externs.js
  scss/partials/_push_notifications_permission_modal.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/push_notifications_permission_modal.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/expo.cljs
  src/oc/web/router.cljs
  src/oc/web/stores/user.cljs
  src/oc/web/utils/user.cljs
Labels: ready for deploy

#989 Hide the google signin button on mobile
  src/oc/web/components/ui/login_wall.cljs
Labels: ready for deploy

#991 Fix secure activity
  scss/partials/_secure_activity.scss
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/utils/comment.cljs
Labels: URGENT, ready for deploy
