Repository open-company/open-company-web, pull requests merged in 2019-04, with the labels that each got.

#845 Tablet navigation fix
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/navigation_sidebar.cljs
Labels: ready for deploy

#814 Debounce scroll
  src/oc/web/lib/utils.cljs
  src/oc/web/mixins/ui.cljs
Labels: reviewing

#843 Content visibility settings
  resources/public/img/ML/carrot_checkbox_mark.svg
  scss/modules/_colors.scss
  scss/partials/_activity_share.scss
  scss/partials/_carrot_checkbox.scss
  scss/partials/_carrot_switch.scss
  scss/partials/_org_settings.scss
  scss/partials/_org_settings_main_panel.scss
  scss/partials/_reminders.scss
  scss/partials/_section_editor.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/section.cljs
  src/oc/web/api.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/carrot_checkbox.cljs
  src/oc/web/components/ui/carrot_switch.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/components/ui/section_editor.cljs
Labels: ready for deploy

#852 Fix share popup position.
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
Labels: URGENT, ready for deploy

#847 Fixed the regex for the email and domain validation in the html forms.
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/org_settings_invite_panel.cljs
  src/oc/web/components/ui/org_settings_main_panel.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for review
