Repository open-company/open-company-web, pull requests merged in 2019-10, with the labels that each got.

#1040 Use Intercom for NUX
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/jwt.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/lib/chat.cljs
Labels: URGENT, reviewing

#1039 Virtualized stream (perf improvement)
  build.boot
  scss/mixins/_activity.scss
  scss/partials/_stream_item.scss
  scss/vars/main.scss
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/lazy_stream.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/lib/react_utils.cljs
  src/oc/web/mixins/activity.cljs
Labels: reviewing

#1041 Optimize Slack and FileStack image URLs where appropriate
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/org_avatar.cljs
  src/oc/web/components/ui/user_avatar.cljs
  src/oc/web/images.cljs
Labels: ready for deploy

#1048 Fix comments summary
  src/oc/web/stores/comment.cljs
Labels: URGENT, ready for deploy

#1043 Read/unread background tweaks
  src/oc/web/components/stream_item.cljs
Labels: low-hanging fruit, ready for deploy

#1052 Fix the comment mobile menu.
  src/oc/web/components/stream_comments.cljs
Labels: URGENT, ready for deploy

#1051 Fix org switch
  src/oc/web/components/ui/org_avatar.cljs
Labels: URGENT, reviewing

#1044 Set slack login redirect-uri to expo deep link when on mobile
  src/oc/web/actions/user.cljs
  src/oc/web/components/ui/login_wall.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: ready for deploy

#1045 Fix signup and invite style on mobile
  scss/partials/_onboard_wrapper.scss
  src/oc/web/components/ui/onboard_wrapper.cljs
Labels: URGENT, ready for deploy

#1046 Post authoring tweaks
  resources/public/img/ML/follow_up_icon_white.svg
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.css
  scss/mixins/_activity.scss
  scss/modules/_colors.scss
  scss/partials/_carrot_abstract.scss
  scss/partials/_cmail.scss
  scss/partials/_post_to_button.scss
  scss/public/css/app.main.scss
  src/oc/web/components/carrot_abstract.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/post_to_button.cljs
  src/oc/web/lib/utils.cljs
Labels: ready for deploy

#1053 Fix save to new board
  src/oc/web/components/cmail.cljs
Labels: URGENT, ready for deploy

#1049 Expanded post tweaks
  resources/public/img/ML/more_menu_new_share.svg
  scss/partials/_add_comment.scss
  scss/partials/_expanded_post.scss
  scss/partials/_more_menu.scss
  scss/partials/_stream_comments.scss
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/more_menu.cljs
Labels: ready for deploy

#1050 Comment action buttons and NEW label
  resources/public/img/ML/comment_react_emoji.svg
  resources/public/img/ML/comment_reply.svg
  resources/public/img/ML/comment_share.svg
  scss/partials/_add_comment.scss
  scss/partials/_expanded_post.scss
  scss/partials/_stream_comments.scss
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/components/ui/more_menu.cljs
Labels: reviewing

#1047 Font size spacing tweaks
  scss/mixins/_activity.scss
  scss/mixins/_org.scss
  scss/partials/_add_comment.scss
  scss/partials/_carrot_abstract.scss
  scss/partials/_cmail.scss
  scss/partials/_comments_summary.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_expanded_post.scss
  scss/partials/_navbar.scss
  scss/partials/_reactions.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_item.scss
  scss/vars/main.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/paginated_stream.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/lib/utils.cljs
Labels: low-hanging fruit, ready for deploy

#1057 Typo fix: Seach → Search
  src/oc/web/components/ui/giphy_picker.cljs
Labels: ready for deploy

#1034 What's new widget (desktop)
  src/oc/web/components/ui/menu.cljs
  src/oc/web/lib/whats_new.cljs
Labels: ready for deploy

#1037 Production dev tools
  build.boot
Labels: ready for deploy
