Repository open-company/open-company-web, pull requests merged in 2019-05, with the labels that each got.

#859 Bump boot-cljs-repl deps and include instructions for development with emacs+cider
  README.md
  build.boot
Labels: ready for review

#851 Notification light theme
  scss/partials/_notifications.scss
  src/oc/web/components/ui/notifications.cljs
Labels: Carrot 2.0, reviewing

#863 Better image handling
  scss/mixins/_activity.scss
  scss/partials/_expanded_post.scss
  scss/partials/_stream_item.scss
  src/oc/web/components/expanded_post.cljs
Labels: Carrot 2.0, reviewing

#865 Remove thumbs-up control from comments
  scss/partials/_stream_comments.scss
  src/oc/web/components/stream_comments.cljs
Labels: Carrot 2.0, reviewing

#853 Why it matters
  resources/public/img/ML/cmail_close.svg
  resources/public/img/ML/cmail_fullscreen_close.svg
  resources/public/img/ML/cmail_fullscreen_collapse.svg
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/mixins/_activity.scss
  scss/modules/_colors.scss
  scss/partials/_cmail.scss
  scss/partials/_expanded_post.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/api.cljs
  src/oc/web/components/all_posts.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/sections_picker.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/mixins/ui.cljs
Labels: Carrot 2.0, ready for deploy

#862 Foc hover fixes
  scss/partials/_dashboard_layout.scss
  scss/partials/_stream_item.scss
Labels: Carrot 2.0, ready for deploy

#861 Digest and public post refresh
  scss/partials/_secure_activity.scss
  scss/partials/_stream_item.scss
  src/oc/web/components/secure_activity.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/utils/comment.cljs
Labels: Carrot 2.0, reviewing

#856 Mark as read
  resources/public/js/externs.js
  scss/partials/_expanded_post.scss
  scss/partials/_more_menu.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/routing.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/api.cljs
  src/oc/web/components/all_posts.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/section_stream.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/local_settings.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/stores/section.cljs
  src/oc/web/utils/activity.cljs
Labels: Carrot 2.0

#858 Inline media picker
  resources/public/img/ML/media_photo.png
  resources/public/img/ML/media_video.png
  resources/public/js/static-js.js
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.css
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  resources/public/lib/js-utils/pasteHtmlAtCaret.js
  scss/partials/_cmail.scss
  scss/partials/_media_video_modal.scss
  scss/partials/_multi_picker.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/emoji_picker.cljs
  src/oc/web/components/ui/multi_picker.cljs
Labels: Carrot 2.0, reviewing

#868 Remove NUX message from expanded post
  src/oc/web/components/dashboard_layout.cljs
Labels: Carrot 2.0, reviewing

#869 Fix drafts icon
  resources/public/img/ML/drafts_icon_grey.svg
  scss/partials/_navigation_sidebar.scss
  src/oc/web/lib/whats_new.cljs
Labels: Carrot 2.0, reviewing

#867 Fix menu position
  scss/partials/_comments_summary.scss
  scss/partials/_expanded_post.scss
  scss/partials/_more_menu.scss
  scss/partials/_stream_item.scss
  scss/partials/_wrt.scss
  src/oc/web/components/stream_item.cljs
Labels: Carrot 2.0

#866 Settings back
  resources/public/js/externs.js
  resources/public/lib/print_ascii.js
  scss/partials/_recurring_updates_modal.scss
  scss/partials/_section_editor.scss
  scss/partials/_wrt.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/org.cljs
  src/oc/web/actions/reminder.cljs
  src/oc/web/actions/section.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/edit_recurring_update_modal.cljs
  src/oc/web/components/integrations_settings_modal.cljs
  src/oc/web/components/invite_settings_modal.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/org_settings.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/recurring_updates_modal.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/ui/empty_org.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/notifications.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/sections_picker.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/components/user_notifications_modal.cljs
  src/oc/web/components/user_profile.cljs
  src/oc/web/components/user_profile_modal.cljs
  src/oc/web/components/user_profile_notifications_tab.cljs
  src/oc/web/core.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/utils/dom.cljs
Labels: Carrot 2.0, ready for deploy

#871 Fix post preview rounded corners
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
Labels: Carrot 2.0, ready for deploy

#878 Update video embed
  scss/partials/_media_video_modal.scss
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/media_video_modal.cljs
Labels: Carrot 2.0, ready for deploy

#870 Fix org name
  scss/mixins/_org.scss
  scss/partials/_org_settings_modal.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_secure_activity.scss
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/org_avatar.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
Labels: Carrot 2.0, ready for review

#874 Writing experience
  scss/mixins/_activity.scss
  scss/partials/_cmail.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_attachments.scss
Labels: Carrot 2.0

#873 Fix FoC borders
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
Labels: Carrot 2.0

#875 Update sections picker
  scss/partials/_cmail.scss
  scss/partials/_sections_picker.scss
  src/oc/web/components/ui/sections_picker.cljs
Labels: Carrot 2.0, awaiting revision

#876 FoC attachments update
  scss/partials/_stream_item.scss
  src/oc/web/components/stream_item.cljs
  src/oc/web/lib/utils.cljs
Labels: Carrot 2.0

#877 Public post footer
  scss/partials/_secure_activity.scss
  src/oc/web/components/secure_activity.cljs
Labels: Carrot 2.0, reviewing

#860 Gif picker
  build.boot
  resources/public/img/ML/media_gif.png
  resources/public/img/ML/media_gif.svg
  resources/public/img/ML/media_photo.svg
  resources/public/img/ML/media_video.svg
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.css
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/partials/_giphy_picker.scss
  scss/public/css/app.main.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/local_settings.cljs
Labels: Carrot 2.0, ready for review

#879 Comment 😀 reactions
  resources/public/img/ML/comment_delete_can.svg
  resources/public/img/ML/comment_edit_pen.svg
  resources/public/img/ML/comment_react_emoji.svg
  resources/public/img/ML/comment_share.svg
  scss/partials/_add_comment.scss
  scss/partials/_expanded_post.scss
  scss/partials/_post_modal.scss
  scss/partials/_stream_comments.scss
  scss/public/css/app.main.scss
  src/oc/web/actions/comment.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/post_modal.cljs
  src/oc/web/components/reactions.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/stores/comment.cljs
  src/oc/web/stores/reaction.cljs
  src/oc/web/utils/comment.cljs
  src/oc/web/utils/reaction.cljs
Labels: Carrot 2.0, ready for review

#882 Carrot 2 fixes
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/api.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_item.cljs
Labels: Carrot 2.0, reviewing

#887 Web font
  resources/public/CircularWebFont/LLCircular-BoldWeb/LLCircularBoldSub.html
  resources/public/CircularWebFont/LLCircular-BoldWeb/LLCircularBoldWeb.html
  resources/public/CircularWebFont/LLCircular-BoldWeb/Lineto EULA.pdf
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts/lineto-circular-bold.eot
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts/lineto-circular-bold.woff
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts/lineto-circular-bold.woff2
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts_subsetted/lineto-circular-bold.eot
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts_subsetted/lineto-circular-bold.woff
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/fonts_subsetted/lineto-circular-bold.woff2
  resources/public/CircularWebFont/LLCircular-BoldWeb/css/stylesheet.css
  resources/public/CircularWebFont/LLCircular-BookWeb/LLCircularBookSub.html
  resources/public/CircularWebFont/LLCircular-BookWeb/LLCircularBookWeb.html
  resources/public/CircularWebFont/LLCircular-BookWeb/Lineto EULA.pdf
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts/lineto-circular-book.eot
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts/lineto-circular-book.woff
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts/lineto-circular-book.woff2
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts_subsetted/lineto-circular-book.eot
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts_subsetted/lineto-circular-book.woff
  resources/public/CircularWebFont/LLCircular-BookWeb/css/fonts_subsetted/lineto-circular-book.woff2
  resources/public/CircularWebFont/LLCircular-BookWeb/css/stylesheet.css
  resources/public/img/ML/must_see_tag.svg
  scss/mixins/_activity.scss
  scss/modules/_fonts.scss
  scss/partials/_about.scss
  scss/partials/_press_kit.scss
  scss/partials/_pricing.scss
  scss/partials/_shared_misc.scss
  scss/partials/_site_header.scss
  scss/partials/_site_mobile_menu.scss
  scss/partials/_stream_item.scss
  site/oc/core.clj
  site/oc/pages.clj
  src/oc/web/components/cmail.cljs
  src/oc/web/components/stream_item.cljs
Labels: Carrot 2.0, ready for deploy

#885 Navigation tweaks.
  resources/public/img/ML/plus_button_icon.svg
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/ui/navbar.cljs
Labels: Carrot 2.0, ready for deploy

#884 Safari fixes
  resources/public/img/ML/must_see_tag.svg
  scss/mixins/_activity.scss
  scss/partials/_all_caught_up.scss
  scss/partials/_cmail.scss
  src/oc/web/components/cmail.cljs
Labels: Carrot 2.0, ready for deploy

#886 Fix notifications click
  src/oc/web/actions/nux.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/user_notifications.cljs
  src/oc/web/lib/fullstory.cljs
  src/oc/web/utils/org.cljs
  src/oc/web/utils/user.cljs
Labels: Carrot 2.0, reviewing

#888 Small feedback tweaks
  build.boot
  resources/public/img/ML/section_access_private.svg
  resources/public/js/externs.js
  scss/mixins/_activity.scss
  scss/mixins/_reusable.scss
  scss/modules/_fonts.scss
  scss/partials/_activity_move.scss
  scss/partials/_add_comment.scss
  scss/partials/_cmail.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_edit_recurring_update_modal.scss
  scss/partials/_expanded_post.scss
  scss/partials/_invite_settings_modal.scss
  scss/partials/_more_menu.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_notifications.scss
  scss/partials/_section_editor.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/reminder.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/edit_recurring_update_modal.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/ui/activity_move.cljs
  src/oc/web/components/ui/media_video_modal.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/stores/search.cljs
  src/oc/web/utils/reminder.cljs
Labels: Carrot 2.0, reviewing

#891 Fix comment edit
  scss/partials/_stream_comments.scss
  src/oc/web/actions/comment.cljs
  src/oc/web/components/stream_comments.cljs
Labels: Carrot 2.0, awaiting revision

#889 Input fields opacity
  scss/partials/_base.scss
  scss/partials/_cmail.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/edit_recurring_update_modal.cljs
  src/oc/web/components/integrations_settings_modal.cljs
  src/oc/web/components/invite_settings_modal.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/reminders.cljs
  src/oc/web/components/search.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/ui/activity_move.cljs
  src/oc/web/components/ui/activity_share.cljs
  src/oc/web/components/ui/login_overlay.cljs
  src/oc/web/components/ui/media_video_modal.cljs
  src/oc/web/components/ui/onboard_wrapper.cljs
  src/oc/web/components/ui/section_editor.cljs
  src/oc/web/components/ui/slack_channels_dropdown.cljs
  src/oc/web/components/ui/slack_users_dropdown.cljs
  src/oc/web/components/ui/user_type_dropdown.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/components/user_notifications_modal.cljs
  src/oc/web/components/user_profile_modal.cljs
  src/oc/web/stores/activity.cljs
Labels: Carrot 2.0, ready for review

#895 Settings data refresh
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/user.cljs
  src/oc/web/api.cljs
  src/oc/web/components/integrations_settings_modal.cljs
  src/oc/web/components/invite_settings_modal.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/team_management_modal.cljs
  src/oc/web/components/user_notifications_modal.cljs
  src/oc/web/components/user_profile_modal.cljs
Labels: Carrot 2.0

#890 Carrot 2.0 responsive web
  scss/mixins/_org.scss
  scss/modules/_colors.scss
  scss/partials/_activity_share.scss
  scss/partials/_add_comment.scss
  scss/partials/_base.scss
  scss/partials/_cmail.scss
  scss/partials/_comments_summary.scss
  scss/partials/_dashboard_layout.scss
  scss/partials/_edit_recurring_update_modal.scss
  scss/partials/_empty_board.scss
  scss/partials/_expanded_post.scss
  scss/partials/_integrations_settings_modal.scss
  scss/partials/_invite_settings_modal.scss
  scss/partials/_menu.scss
  scss/partials/_more_menu.scss
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_org_dashboard.scss
  scss/partials/_org_settings_modal.scss
  scss/partials/_orgs_dropdown.scss
  scss/partials/_recurring_updates_modal.scss
  scss/partials/_section_editor.scss
  scss/partials/_secure_activity.scss
  scss/partials/_stream_comments.scss
  scss/partials/_stream_item.scss
  scss/partials/_team_management_modal.scss
  scss/partials/_user_avatar.scss
  scss/partials/_user_notifications.scss
  scss/partials/_user_notifications_modal.scss
  scss/partials/_user_profile_modal.scss
  scss/partials/_wrt.scss
  scss/vars/main.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/nav_sidebar.cljs
  src/oc/web/actions/reaction.cljs
  src/oc/web/actions/team.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/navigation_sidebar.cljs
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/stream_comments.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/menu.cljs
  src/oc/web/components/ui/more_menu.cljs
  src/oc/web/components/ui/navbar.cljs
  src/oc/web/components/ui/orgs_dropdown.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/lib/responsive.cljs
  src/oc/web/mixins/ui.cljs
  src/oc/web/stores/activity.cljs
  src/oc/web/stores/search.cljs
Labels: Carrot 2.0, ready for review

#892 Carrot 2 picker views
  scss/partials/_cmail.scss
  scss/partials/_giphy_picker.scss
  scss/partials/_media_video_modal.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/rich_body_editor.cljs
  src/oc/web/components/ui/giphy_picker.cljs
  src/oc/web/components/ui/media_video_modal.cljs
Labels: Carrot 2.0, ready for review

#896 Carrot 2 fix 404
  src/oc/web/actions/routing.cljs
  src/oc/web/components/expanded_post.cljs
Labels: Carrot 2.0, ready for review

#893 Carrot 2 mobile compose
  resources/public/img/ML/compose_icon_grey.svg
  scss/partials/_cmail.scss
  scss/partials/_navbar.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/stream_item.cljs
  src/oc/web/components/ui/comments_summary.cljs
  src/oc/web/components/ui/navbar.cljs
Labels: Carrot 2.0, ready for review

#880 WST updates
  src/oc/web/components/org_dashboard.cljs
  src/oc/web/components/ui/wrt.cljs
  src/oc/web/dispatcher.cljs
  src/oc/web/stores/activity.cljs
Labels: Carrot 2.0, ready for deploy

#899 Scroll back to top when opening a post.
  src/oc/web/components/stream_item.cljs
Labels: ready for deploy
