Repository open-company/open-company-web, pull requests merged in 2020-04, with the labels that each got.

#1131 Polls
  resources/public/img/ML/close_x.svg
  resources/public/img/ML/close_x@dark.svg
  resources/public/img/ML/media_poll.svg
  resources/public/img/ML/media_poll@dark.svg
  resources/public/img/ML/poll_voted_check.svg
  resources/public/img/ML/poll_voted_check_dark.svg
  resources/public/js/externs.js
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.css
  resources/public/lib/MediumEditorExtensions/MediumEditorMediaPicker/MediaPicker.js
  scss/mixins/_activity.scss
  scss/modules/_theme.scss
  scss/partials/_stream_item.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/actions/poll.cljs
  src/oc/web/api.cljs
  src/oc/web/components/cmail.cljs
  src/oc/web/components/dashboard_layout.cljs
  src/oc/web/components/expanded_post.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/poll.cljs
  src/oc/web/lib/utils.cljs
  src/oc/web/local_settings.cljs
  src/oc/web/utils/medium_editor_media.cljs
  src/oc/web/utils/poll.cljs
Labels: ready for deploy

#1153 Fixes punchlist
  resources/public/img/ML/bookmarks_icon_white.svg
  resources/public/img/ML/digest_icon_green.svg
  resources/public/img/ML/drafts_icon_grey.svg
  scss/mixins/_activity.scss
  scss/partials/_expanded_post.scss
  scss/partials/_navigation_sidebar.scss
  src/oc/web/components/expanded_post.cljs
Labels: ready for deploy

#1154 Invite picker email domain
  scss/partials/_email_domains.scss
  scss/partials/_invite_picker_modal.scss
  scss/partials/_invite_slack_modal.scss
  scss/partials/_org_settings_modal.scss
  scss/public/css/app.main.scss
  src/oc/web/components/invite_picker_modal.cljs
  src/oc/web/components/org_settings_modal.cljs
  src/oc/web/components/ui/email_domains.cljs
Labels: ready for deploy

#1156 Production fixes
  scss/partials/_login_button.scss
  scss/partials/_navbar.scss
  scss/partials/_navigation_sidebar.scss
  scss/partials/_secure_activity.scss
  src/oc/web/actions/activity.cljs
  src/oc/web/components/secure_activity.cljs
  src/oc/web/components/ui/login_button.cljs
  src/oc/web/components/ui/navbar.cljs
Labels: URGENT, low-hanging fruit, ready for deploy

#1158 Store UTM creds in org
  resources/public/js/externs.js
  resources/public/js/static-js.js
  resources/public/lib/autotrack/google-analytics.js
  site/oc/pages.clj
  src/oc/web/actions/org.cljs
  src/oc/web/api.cljs
  src/oc/web/lib/cookies.cljs
Labels: ready for deploy

#1157 Fix disappearing placeholder
  scss/partials/_add_comment.scss
  scss/partials/_cmail.scss
  src/oc/web/components/cmail.cljs
  src/oc/web/components/ui/add_comment.cljs
  src/oc/web/utils/dom.cljs
Labels: URGENT, ready for deploy

#1159 Remove gaps from mobile
  scss/partials/_dashboard_layout.scss
  scss/partials/_navbar.scss
  scss/partials/_stream_item.scss
  scss/vars/main.scss
  src/oc/web/components/paginated_stream.cljs
Labels: ready for deploy
